// Auto-generated from nigerian_universities_list.xlsx
// 265 active Nigerian universities (Federal, State, Private)
const List<String> kNigerianUniversities = [
  'Abdulkadir Kure University Minna',
  'Abia State University, Uturu',
  'Abubakar Tafawa Balewa University, Bauchi',
  'Achievers University, Owo',
  'Adamawa State University Mubi',
  'Adekunle Ajasin University, Akungba',
  'Adeleke University, Ede',
  'Admiralty University Ibusa',
  'Afe Babalola University, Ado-Ekiti',
  'African University of Science & Technology, Abuja',
  'Ahmadu Bello University, Zaria',
  'Ahman Pategi University',
  'Air Force Institute of Technology, Kaduna',
  'Ajayi Crowther University, Ibadan',
  'Akwa Ibom State University, Ikot Akpaden',
  'Al-Ansar University Maiduguri',
  'Al-Hikmah University, Ilorin',
  'Al-Istiqama University Sumaila',
  'Al-Ma’arif University Potiskum',
  'Al-Qalam University, Katsina',
  'Alex Ekwueme Federal University',
  'Amaj University Kwali',
  'Ambrose Alli University, Ekpoma',
  'American University of Nigeria, Yola',
  'Anan University Kwall',
  'Anchor University Ayobo',
  'Arthur Javis University Akpabuyo',
  'Atta-Iga University',
  'Augustine University, Ilara',
  'Ave Maria University Piyanko',
  'Azman University Kano',
  'Babamasta University',
  'Babcock University, Ilishan-Remo',
  'Bamidele Olumilua University of Education Science and Technology Ikere',
  'Bauchi State University, Gadau',
  'Bayelsa Medical University',
  'Bayero University, Kano',
  'Baze University Abuja',
  'Baze University, Abuja',
  'Bells University of Technology, Otta',
  'Benson Idahosa University, Benin City',
  'Benue State University, Makurdi',
  'Bingham University New Karu',
  'Bingham University, New Karu',
  'Borno State University',
  'Bornu State University',
  'Bowen University, Iwo',
  'CETEP City University, Lagos',
  'Caleb University, Lagos',
  'Canadian University of Nigeria Abuja',
  'Capital City University Kano',
  'Caritas University, Enugu',
  'Chrisland University, Owode',
  'Christopher University Mowe',
  'Chukwuemeka Odumegwu Ojukwu University, Uli',
  'City University of Technology Kaduna',
  'Claretian University of Nigeria Nekede',
  'Clifford University Owerrinta',
  'Coal City University Enugu',
  'Confluence University of Science and Technology Osara',
  'Covenant University Ota',
  'Crawford University Igbesa',
  'Crescent University, Abeokuta',
  'Cross River State University of Technology, Calabar',
  'Crown Hill University Eiyenkorin',
  'Delta State University Abraka',
  'Delta State University of Science and Technology Ozoro',
  'Delta University of Science and Agbor',
  'Dennis Osadebay University Asaba',
  'Dominican University Ibadan',
  'Eastern Palm University Ogboko',
  'Ebonyi State University, Abakaliki',
  'Edo State University Uzairue',
  'Edusoko University Bida',
  'Ekiti State University',
  'El-Amin University Minna',
  'Elizade University, Ilara-Mokin',
  'Emanuel Alayande University of Education Oyo',
  'Enugu State University of Science and Technology',
  'Evangel University, Akaeze',
  'Federal University Gashua, Yobe',
  'Federal University of Agriculture, Zuru',
  'Federal University of Health Sciences, Azare',
  'Federal University of Health Sciences, Ila Orangun',
  'Federal University of Health Sciences, Otukpo',
  'Federal University of Health Technology, Otukpo',
  'Federal University of Petroleum Resources, Effurun',
  'Federal University of Technology, Akure',
  'Federal University of Technology, Babura',
  'Federal University of Technology, Ikot Abasi',
  'Federal University of Technology, Minna',
  'Federal University of Technology, Owerri',
  'Federal University, Birnin Kebbi',
  'Federal University, Dutse, Jigawa State',
  'Federal University, Dutsin-Ma, Katsina',
  'Federal University, Gusau, Zamfara',
  'Federal University, Kashere, Gombe State',
  'Federal University, Lafia, Nasarawa State',
  'Federal University, Lokoja, Kogi State',
  'Federal University, Ndufu-Alike, Ebonyi State',
  'Federal University, Otuoke, Bayelsa',
  'Federal University, Oye-Ekiti, Ekiti State',
  'Federal University, Wukari, Taraba State',
  'First Technical University Ibadan',
  'Fountain University, Oshogbo',
  'Franco-British International University',
  'Gerar University of Medical Sciences',
  'Godfrey Okoye University, Ugwuomu-Nike',
  'Gombe State Univeristy',
  'Gombe State University of Science and Technology',
  'Gregory University, Uturu',
  'Guinness University',
  'Hallmark University, Ijebu Itele',
  'Havilla University Nde-Ikom',
  'Hensard University Toru-Orua',
  'Hillside University of Science and Technology',
  'Huda University Gusau',
  'Igbinedion University Okada',
  'Ignatius Ajuru University of Education Rumuolumeni',
  'Imo State University, Owerri',
  'Joseph Ayo Babalola University, Ikeji-Arakeji',
  'Kaduna State University',
  'Kano University of Science & Technology, Wudil',
  'Karl-Kumm University',
  'Karl-Kumm University Vom',
  'Khadija University Majia',
  'Khalifa Isiyaku Rabiu University Kano',
  'Khokhmah University Makurdi',
  'Kings University, Ode Omu',
  'Kogi State University Anyigba',
  'Kogi State University Kabba',
  'Kola Daisi University Ibadan',
  'Kwara State University, Ilorin',
  'Kwararafa University, Wukari',
  'Ladoke Akintola University of Technology, Ogbomoso',
  'Lagos State University of Education',
  'Lagos State University of Science and Technology',
  'Lagos State University, Ojo',
  'Landmark University Omu-Aran',
  'Landmark University, Omu-Aran',
  'Lead City University, Ibadan',
  'Legacy University Okija',
  'Lighthouse University',
  'Lux Mundi University',
  'Madonna University, Okija',
  'Maduka University',
  'Maranatha University',
  'Maranatha University Mgbidi',
  'Margaret Lawrence University',
  'Maryamm Abacha American University Kano',
  'Mcpherson University, Seriki Sotayo',
  'Mercy Medical University',
  'Mewar International University',
  'Mewar University',
  'Michael Okpara University of Agricultural Umudike',
  'Micheal & Cecilia Ibru University',
  'Modibbo Adama University of Technology, Yola',
  'Montaigine University',
  'Moshood Abiola University of Science and Technology Abeokuta',
  'Mountain Top University',
  'Mudiame University Irrua',
  'Nasarawa State University Keffi',
  'National Open University of Nigeria, Abuja',
  'Niger Delta University Yenagoa',
  'Niger State University of Education',
  'Nigerian Army University Biu',
  'Nigerian Defence Academy Kaduna',
  'Nile University of Nigeria, Abuja',
  'Nnamdi Azikiwe University, Awka',
  'Nok University Kachia',
  'North West University Sokoto',
  'Novena University, Ogume',
  'Obafemi Awolowo University, Ile-Ife',
  'Obong University, Obong Ntak',
  'Oduduwa University, Ipetumodu',
  'Olabisi Onabanjo University, Ago Iwoye',
  'Ondo State University of Medical Sciences',
  'Ondo State University of Science and Technology Okitipupa',
  'Osun State University Osogbo',
  'Oyo State Technical University Ibadan',
  'PAMO University of Medical Sciences',
  'Pacesetters University Enugu',
  'Pan-Atlantic University, Lagos',
  'Paul University, Awka',
  'Peaceland University',
  'Pen Resource University Gombe',
  'Peter University',
  'Philomath University Abuja',
  'Plateau State University Bokkos',
  'Police Academy Wudil',
  'Prime University',
  'Rayhaan University',
  'Redeemer\'s University, Ede',
  'Renaissance University, Enugu',
  'Rhema University, Obeama-Asa',
  'Ritman University, Ikot Ekpene',
  'Rivers State University',
  'Safa University',
  'Salem University, Lokoja',
  'Sam Maris University',
  'Samuel Adegboyega University, Ogwa',
  'Sa’adatu Rimi University of Education Kano',
  'Shehu Shagari University of Education Sokoto',
  'Sijuwade University',
  'Skyline University Nigeria',
  'Sokoto State University',
  'Southwestern University, Oku Owa',
  'Sparkling University',
  'Spiritan University Nneochi',
  'Sports University',
  'Sports University Idumuje-Ugboko',
  'Springfield University',
  'Standard University',
  'Star University',
  'State University of Medical and Applied Sciences',
  'State University of Medical and Applied Sciences Enugu',
  'Stephen University',
  'Sule Lamido University, Kafin Hausa',
  'Summit University, Offa',
  'Tai Solarin University of Education Ijebu Ode',
  'Tansian University',
  'Tansian University, Umunya',
  'Taraba State University, Jalingo',
  'The Duke Medical University',
  'The Gateway University',
  'Thomas Adewumi University',
  'Thomas Adewumi University Oko-Irese',
  'Topfaith University Mkpatak',
  'Transatlantic University',
  'Trinity University',
  'Triumph University',
  'Twin-City University',
  'Umaru Musa Yar\'Adua University Katsina',
  'Umaru Musa Yar\'adua University',
  'University of Abuja, Gwagwalada',
  'University of Africa Toru Orua',
  'University of Agriculture and Environmental Sciences Umuagwo',
  'University of Agriculture, Abeokuta',
  'University of Agriculture, Makurdi',
  'University of Benin',
  'University of Calabar',
  'University of Ibadan',
  'University of Ilorin',
  'University of Jos',
  'University of Lagos',
  'University of Maiduguri',
  'University of Mkar, Mkar',
  'University of Nigeria, Nsukka',
  'University of Port-Harcourt',
  'University of Uyo',
  'University on the Niger',
  'Usumanu Danfodiyo University',
  'Venite University Iloro-Ekiti',
  'Veritas University, Abuja',
  'Vision University',
  'Wacot University',
  'Wellspring University, Evbuobanosa',
  'Wesley University',
  'Wesley University of Science & Technology, Ondo',
  'Western Delta University',
  'Western Delta University, Oghara',
  'Wigwe University Isiokpo',
  'Yobe State University, Damaturu',
  'Yusuf Maitama Sule University Kano',
  'Zamfara State University',
];